### ISSUE TITLE
Question: _pickle.UnpicklingError: invalid load key, 'v'

### ISSUE THREAD

**Issue by dotchang** [DwangoMediaVillage/3dpose_gan#1]
I tried to run the project on Ubuntu 16.04, but I met an error.
The environment is clean installed one.
Could you give me some advices on what I should do with this error?

----- logs ------
cvl@cvl-All-Series:~/workspace/3dpose_gan$ python bin/demo.py your/image.png --lift_model sample/gen_epoch_500.npz --model pose_iter_440000.caffemodel --proto2d pose_deploy_linevec.prototxt
MODEL: generator, N_OUT: 17, N_UNIT: 1024
Traceback (most recent call last):
  File "/home/cvl/.pyenv/versions/3.6.1/lib/python3.6/site-packages/numpy/lib/npyio.py", line 428, in load
    return pickle.load(fid, **pickle_kwargs)
_pickle.UnpicklingError: invalid load key, 'v'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bin/demo.py", line 201, in <module>
    main(args)
  File "bin/demo.py", line 157, in main
    chainer.serializers.load_npz(args.lift_model, model)
  File "/home/cvl/.pyenv/versions/3.6.1/lib/python3.6/site-packages/chainer/serializers/npz.py", line 151, in load_npz
    with numpy.load(file) as f:
  File "/home/cvl/.pyenv/versions/3.6.1/lib/python3.6/site-packages/numpy/lib/npyio.py", line 431, in load
    "Failed to interpret file %s as a pickle" % repr(file))
OSError: Failed to interpret file 'sample/gen_epoch_500.npz' as a pickle

cvl@cvl-All-Series:~/workspace/3dpose_gan$ ls sample/gen_epoch_500.npz 
sample/gen_epoch_500.npz
cvl@cvl-All-Series:~/workspace/3dpose_gan$ pip install -U pickle
Collecting pickle
  Could not find a version that satisfies the requirement pickle (from versions: )
No matching distribution found for pickle
cvl@cvl-All-Series:~/workspace/3dpose_gan$ pip install -U scipy
Requirement already up-to-date: scipy in /home/cvl/.pyenv/versions/3.6.1/lib/python3.6/site-packages
Requirement already up-to-date: numpy>=1.8.2 in /home/cvl/.pyenv/versions/3.6.1/lib/python3.6/site-packages (from scipy)
cvl@cvl-All-Series:~/workspace/3dpose_gan$ python -V
Python 3.6.1

**Comment by kogaki** [comment]
Thank you for your detailed information! I'll try reproduce the errors.

**Comment by kogaki** [comment]
I think `git-lfs` is not installed in your environment. Could you try again after install it?

**Comment by dotchang** [comment]
I download gen_epoch_500.npz as raw file directly, it solved.Thank you!

**Comment by getsanjeev** [comment]
@dotchang Can you please tell, what exactly you have done to solve this?

**Comment by Spenhouet** [comment]
To solve this I simply had to run `git-lfs pull`.
