### ISSUE TITLE
Cannot download gen_epoch_500.npz

### ISSUE THREAD

**Issue by horefice** [DwangoMediaVillage/3dpose_gan#6]
It seems the git lfs has a small quota, which has been exceeded. Could you provided another way to get the gen_epoch_500.npz?

`batch response: This repository is over its data quota. Purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/DwangoMediaVillage/3dpose_gan.git/info/lfs'`

**Comment by yasunorikudo** [comment]
Sorry for inconvenience.
The problem has been solved.

**Comment by kogaki** [comment]
We've purchased additional data pack, so I will close this issue.
Thank you for your bug report @horefice .
