### ISSUE TITLE
Typo in running command

### ISSUE THREAD

**Issue by sunshineatnoon** [DwangoMediaVillage/3dpose_gan#9]
Thanks for sharing this work. When running the demo, I guess the right command is 

```
python bin/demo.py sample/image.png --lift_model sample/gen_epoch_500.npz --model2d pose_iter_440000.caffemodel --proto2d openpose_pose_coco.prototxt
```
One argument is `model2d` instead of `model`.

**Comment by kogaki** [comment]
@sunshineatnoon 
Thanks! I've fixed typo now.

Fortunately, this typo has no effect because we are using `argparse` library which has `prefix-matching` feature 
 (https://docs.python.org/dev/library/argparse.html#prefix-matching).
